### ISSUE TITLE
crash with status 503 service unavailable during "Migration Files, Uploading Files"

### ISSUE THREAD

**Issue by xshadowlegendx** [directus-community/migration-tool#10]
migration machine:

MacBook Pro v11.1 big sur
nodejs: v14.15.4

I am migrating v8 to v9 on my local machine, so I take v8 backup from production, make sure everything is restored properly(data, files etc) and after migrate v8 to v9 on local machine, taking v9 backup from local and migrate/restore it onto production

below is the `docker-compose.yml` setup on my local machine to do the migration

```
version: '2.4'

volumes:
  directus_db:
  directus_uploads:
  directus_v8_uploads:

networks:
  directus_db:
  directus_v8_db:

services:
  directus_db:
    image: postgres:12-alpine
    container_name: directus_db
    networks:
      - directus_db
    volumes:
      - directus_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=directus
      - POSTGRES_DB=directus
      - POSTGRES_PASSWORD=directus
      - PGDATA=/var/lib/postgresql/data/pg_data
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_INITDB_WALDIR=/var/lib/postgresql/data/pg_wal

  directus:
    image: directus/directus:v9.0.0-rc.53
    networks:
      - directus_db
    ports:
      - 8080:8055
    environment:
      DIRECTUS_APP_ENV: production
      DB_CLIENT: pg
      DB_HOST: directus_db
      DB_PORT: 5432
      DB_USER: directus
      DB_PASSWORD: directus
      DB_DATABASE: directus
    volumes:
      - ./data/config:/var/directus/config:ro
      - directus_uploads:/var/directus/public/uploads

  mysql:
    image: mysql:5.7
    container_name: directus_v8_db
    networks:
      - directus_v8_db
    environment:
      MYSQL_USER: directus
      MYSQL_DATABASE: directus
      MYSQL_PASSWORD: directus
      MYSQL_ROOT_PASSWORD: directus

  directus_v8:
    image: directus/directus:v8-apache
    networks:
      - directus_v8_db
    ports:
      - 8081:80
    environment:
      DIRECTUS_APP_ENV: production
      DIRECTUS_DATABASE_HOST: mysql
      DIRECTUS_DATABASE_PORT: 3306
      DIRECTUS_DATABASE_NAME: directus
      DIRECTUS_DATABASE_USERNAME: directus
      DIRECTUS_DATABASE_PASSWORD: directus
      DIRECTUS_AUTH_PUBLICKEY: some random secret
      DIRECTUS_AUTH_SECRETKEY: another random secret
    volumes:
      - directus_v8_uploads:/var/directus/public/uploads
```

running migration in the console

```
node index.js
Migrating http://localhost:8081/my-awesome-project (v8) to http://localhost:8080 (v9)...
  ✔ Migrating Schema
  ❯ Migration Files
    ✔ Getting File Count
    ❯ Uploading Files
      ✖ Uploading files 1—100
        → Request failed with status code 503
        Uploading files 101—200
        Uploading files 101—200
        Uploading files 201—300
        Uploading files 301—400
        Uploading files 401—500
        Uploading files 501—600
        Uploading files 601—700
        Uploading files 701—800
        Uploading files 801—900
        Uploading files 901—1000
        Uploading files 1001—1100
        Uploading files 1101—1200
        Uploading files 1201—1300
        Uploading files 1301—1400
        Uploading files 1401—1500
        Uploading files 1501—1600
    Migrating Users
    Migrating Data
Error: Request failed with status code 503
    at createError (/private/tmp/my-awesome-project-backups/migration-tool/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/private/tmp/my-awesome-project-backups/migration-tool/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/private/tmp/my-awesome-project-backups/migration-tool/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: '/files/import',
    method: 'post',
    data: '{"url":"http://localhost:8081/my-awesome-project/assets/ah39dolmx8o4sckg","data":{"filename_download":"book(1).svg","title":"Book(1)","description":""}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      Authorization: 'Bearer 9C18B2F8-AA92-403A-9DBC-1CC3F3288368',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 142
    },
    baseURL: 'http://localhost:8080',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'localhost',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 303,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /files/import HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json;charset=utf-8\r\n' +
      'Authorization: Bearer 9C18B2F8-AA92-403A-9DBC-1CC3F3288368\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Content-Length: 142\r\n' +
      'Host: localhost:8080\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/files/import',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 503,
      statusMessage: 'Service Unavailable',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://localhost:8080/files/import',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'localhost',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 142,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://localhost:8080/files/import',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  response: {
    status: 503,
    statusText: 'Service Unavailable',
    headers: {
      'x-powered-by': 'Directus',
      vary: 'Origin',
      'access-control-allow-credentials': 'true',
      'access-control-expose-headers': 'Content-Range',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '184',
      etag: 'W/"b8-0FjMpR/HtK8aMYHaOFBn5EJovcs"',
      date: 'Sun, 04 Apr 2021 07:36:20 GMT',
      connection: 'close'
    },
    config: {
      url: '/files/import',
      method: 'post',
      data: '{"url":"http://localhost:8081/my-awesome-project/assets/ah39dolmx8o4sckg","data":{"filename_download":"book(1).svg","title":"Book(1)","description":""}}',
      headers: [Object],
      baseURL: 'http://localhost:8080',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'POST /files/import HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=utf-8\r\n' +
        'Authorization: Bearer 9C18B2F8-AA92-403A-9DBC-1CC3F3288368\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 142\r\n' +
        'Host: localhost:8080\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/files/import',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { errors: [Array] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON],
  context: [Object: null prototype] {
    collections: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    relations: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    fileCount: 1551,
    fileMap: {}
  }
}
```

the migration crashed half way and only data model are being imported from v8 to v9

edit0: I also made sure the url to the file exists by copy and paste it into browser `http://localhost:8081/my-awesome-project/assets/ah39dolmx8o4sckg` and both user token are admin level

edit1: Sorry for silly mistake, so I check logs from directus v9 container, it is trying to download the file from `127.0.0.1:8081` which the directus v9 has no access to directus v8, I will fix it and probably close this issue
